### ISSUE TITLE
Błąd w dokumentacji swagger.yaml /sale/offers publication.status default

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1115]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

Dzień dobry, na stronie portalu https://developer.allegro.pl/about/ można pobrać całą dokumentację zasobów w formie swagger.yaml https://developer.allegro.pl/swagger.yaml

W dokumentacji znajduje się błąd składniowy w strukturze danych. W metodzie do zarządzania ofertami /sale/offers opis parametru name: publication.status powinien definiować wartości domyślne: default: 'ACTIVE,ACTIVATING,ENDED' 

Na początku linii  nr 154 (stan na 25-01-2019) w pliku swagger.yaml brakuje 2 spacji w efekcie element default nie wchodzi w skład elementu schema. Poproszę o dostawie tych 2 spacji celem wyeliminowania błędów generatora open api.

```
  /sale/offers:
	(...)
    get:
      tags:
        - offer-management
      summary: "Get seller's offers"
      description: Search seller's offers by given criteria. Accept header should be set to application/vnd.allegro.beta.v1+json
      operationId: searchOffersUsingGET
      parameters:
        (...)
        - name: publication.status
          in: query
          description: Publication statuses may contain more than one comma separated value
          required: false
          schema:
            type: string
            enum:
              - INACTIVE
              - ACTIVE
              - ACTIVATING
              - ENDED
            default: 'ACTIVE,ACTIVATING,ENDED'
```
