### ISSUE TITLE
Błędy w dokumentacji swagger.yaml

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1233]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

Dzień dobry, na stronie portalu https://developer.allegro.pl/about/ można pobrać całą dokumentację zasobów w formie swagger.yaml https://developer.allegro.pl/swagger.yaml

Po ostatnich zmianach w dokumentacji znajdują się błędy powodujące błędy walidacji generatora open api.

1. W linii nr 5867 (stan na 21-02-2019) w pliku swagger.yaml w definicji obiektu OfferListingDtoV1 we właściwości external jest błąd składniowy zamiast **$req** powinno być **$ref**

```
    OfferListingDtoV1:
      type: object
      properties:
...
        external:
          $req: '#/components/schemas/JustId'
```

2. W linii 3362 (stan na 21-02-2019) zdefiniowana jest niezgodnie ze specyfikacją open api ścieżka autoryzacji oAuth zamiast **deviceCode** powinno być **x-deviceCode** ponieważ specyfikacja open api w standardzie nie przewiduje takiej ścieżki. 

Standardowo są dostępne cztery: implicit, password, clientCredentials, authorizationCode. Natomiast dodatkową x-deviceCode można dodać poprzez rozszerzenie obiektu z prefiksem x-.

Specyfikacja swagger / open api: 
https://swagger.io/specification/#oauth-flows-object
https://swagger.io/specification/#specificationExtensions

```
components:
  securitySchemes:
    bearer-token-for-user:
      type: oauth2
      description: >-
        For more information, see https://developer.allegro.pl/auth/#app to read about authorization code flow
        or https://developer.allegro.pl/auth/#DeviceFlow to read about the device code flow.
      flows:
        authorizationCode:
          authorizationUrl: https://allegro.pl/auth/oauth/authorize
          tokenUrl: https://allegro.pl/auth/oauth/token
          scopes: {}
        deviceCode:
          authorizationUrl: https://allegro.pl/skojarz-aplikacje
          tokenUrl: https://allegro.pl/auth/oauth/token
          scopes: {}
```

 Poproszę o poprawę tych dwóch błędów celem wyeliminowania błędów generatora open api.
