### ISSUE TITLE
odpowiedź z category/parameters nie zgadza się ze schemą

### ISSUE THREAD

**Issue by rafalkrupinski** [allegro/allegro-api#1408]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

https://api.allegro.pl/sale/categories/{categoryId}/parameters
Według swagger.yaml w typie CategoryParameter mapping pola type na podtyp parametru jest:
```yaml
    CategoryParameter:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          INTEGER: '#/components/schemas/IntegerCategoryParameter'
          FLOAT: '#/components/schemas/FloatCategoryParameter'
          STRING: '#/components/schemas/StringCategoryParameter'
          DICTIONARY: '#/components/schemas/DictionaryCategoryParameter'
```

Natomiast w odpowiedzi zapytania pole typ przychodzi z małymi literami.
```json
{"parameters":[{"id":"11323","name":"Stan","type":"dictionary" ...
```
