### ISSUE TITLE
Błędy dokumentacji swagger.yaml /sale/shipping-rates

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1572]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, tworząc nowy cennik dostawy wymagane jest przesłanie listy metod dostaw wraz z wypełnionymi wartościami. 

W [dokumentacji](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST) swagger.yaml obiekt "rates" $ref: '#/components/schemas/ShippingRatesSet' nie jest zdefiniowany jako lista (type: array), tak jak to jest w innych metodach zwracających lub wymagających listy obiektów. 

W efekcie wygenerowany kod na postawie dokumentacji swagger.yaml posiada metodę dodająca nowy cennik z tylko jedną metodą dostawy, zamiast listy.

Problem dotyczy wszystkich metod odwołujących się do definicji $ref: '#/components/schemas/ShippingRatesSet' która powinna definiować listę obiektów (type: array) zamiast pojedyńczy obiekt (type: object).

Proszę o weryfikację i poprawę.

Json z poradnika:
```
curl -X POST \
  https://api.allegro.pl/sale/shipping-rates \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: {token}' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -d '{
    "name": "Nowy cennik dostawy",                              -- wymagane, nazwa 
                                                                danego cennika dostaw
    "rates": [
        {
            "deliveryMethod": {
                "id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93"    -- wymagane, identyfikator 
                                                                danej metody dostawy
            },
            "maxQuantityPerPackage": 1,                         -- wymagane, liczba w paczce
            "firstItemRate": {                                  -- wymagane, cena przesyłki
                "amount": "7.99",
                "currency": "PLN"
            },
            "nextItemRate": {                                   -- wymagane, cena 
                                                                kolejnej sztuki
                "amount": "0.00",
                "currency": "PLN"
            },
            "shippingTime": {                                   -- wymagane, czas dostawy, 
                "from": "PT72H",                                podaj wielokrotność 24H, 
                "to": "PT120H"                                  zgodnie z formatem ISO 8601
            }
        },
        {
            "deliveryMethod": {
                "id": "845efe05-0c96-47c3-a8cb-aa4699c158ce"
            },
            "maxQuantityPerPackage": 10,
            "firstItemRate": {
                "amount": "12.58",
                "currency": "PLN"
            },
            "nextItemRate": {
                "amount": "12.58",
                "currency": "PLN"
            },
            "shippingTime": null
        }
    ]
}'
```
JSON z [dokumentacji](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST)" obiekt rates nie jest listą i nie zwiera nawiasów kwadratowych []

```
{
  "id": "string",
  "name": "string",
  "rates": {
    "deliveryMethod": {
      "id": "string"
    },
    "maxQuantityPerPackage": 1,
    "firstItemRate": {
      "amount": "string",
      "currency": "string"
    },
    "nextItemRate": {
      "amount": "string",
      "currency": "string"
    },
    "shippingTime": {
      "from": "string",
      "to": "string"
    }
  },
  "lastModified": "string"
}
```

Metoda POST /sale/shipping-rates odwołująca się do definicji obiektu $ref: '#/components/schemas/ShippingRatesSet'
```
/sale/shipping-rates:
(. . .)
post:
      tags:
        - Delivery
      summary: "Create a new shipping rates set"
      description:
        'Use this resource to create a new seller''s shipping rates set. More information about this resource you can
         find <a href="../news/2018-08-14-cenniki_dostawy/" target="_blank">here</a>.'
      operationId: createShippingRatesSetUsingPOST
      requestBody:
        description: Shipping rates set
        required: true
        content:
          application/vnd.allegro.public.v1+json:
            schema:
              $ref: '#/components/schemas/ShippingRatesSet'
```

Definicja obiektu $ref: '#/components/schemas/ShippingRatesSet' lecz nie zawiera nigdzie listy (type: array):
```
ShippingRatesSet:
      type: object
      properties:
        id:
          type: string
          description: >-
            Shipping rates set ID (UUID)
            When creating a shipping rates set (Post) the field is ignored.
            It is required when updating (Put) a shipping rates.
        name:
          type: string
          minLength: 1
          maxLength: 64
          description: User defined name of the shipping rates set
        rates:
          type: object
          properties:
            deliveryMethod:
              type: object
              properties:
                id:
                  type: string
                  description: ID of the delivery method
            maxQuantityPerPackage:
              type: integer
              description: >-
                Maximum quantity per package for the given delivery
                method. Minimum value is 1.
              minimum: 1
            firstItemRate:
              type: object
              description: >-
                Rate for the first item in the parcel for the given
                delivery method
              properties:
                amount:
                  type: string
                  description: Amount
                currency:
                  type: string
                  description: ISO 4217 currency code
            nextItemRate:
              type: object
              description: >-
                Rate for every other item, after the first, in the
                same parcel for the given delivery method
              properties:
                amount:
                  type: string
                  description: Amount
                currency:
                  type: string
                  description: ISO 4217 currency code
            shippingTime:
              type: object
              description: >-
                Custom shipping time for the given delivery method. If
                not set the default shipping time for the method is
                used.
              properties:
                from:
                  type: string
                  description: 'ISO 8601 duration format, e.g. P3D for 3 days'
                to:
                  type: string
                  description: 'ISO 8601 duration format, e.g. P3D for 3 days'
          required:
            - deliveryMethod
            - firstItemRate
            - maxQuantityPerPackage
            - nextItemRate
        lastModified:
          type: string
          description: >-
            Date and time of the last modification of the set in UTC
            ISO 8601 format.
            When creating (Post) or updating (Put) a shipping rates set the field is ignored.
```
