### ISSUE TITLE
Błąd dokumentacji swagger.yaml obiekt Delivery additionalInfo 650

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1656]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, dokumentacja swagger.yaml zawiera informacje, że pole z dodatkową informacją o dostawie może zawierać 650 znaków, natomiast na stronie przy wystawianiu aukcji jest 500. Rest api zwraca błąd, że tekst jest za długi prze próbie wysłania 650 znaków.

Proszę o poprawienie dokumentacji.

```
    Delivery:
      type: object
      properties:
        additionalInfo:
          type: string
          maxLength: 650
```
