### ISSUE TITLE
Niepełna dokumentacja ShippingRatesSet.name

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1674]
W dokumentacji i swaggerze jest 
```
name:
          type: string
          minLength: 1
          maxLength: 64
          description: User defined name of the shipping rates set
```

API rzuca błędem 
```
{'errors': [{'code': 'ConstraintViolationException', 'message': 'Unprocessable entity', 'details': None, 'path': 'name', 'userMessage': 'Name contains invalid characters.'}]}
``` 
przy nazwie
```
'name': 'above_free_shipping'
```
oczywiście wywalenie "_" pomogło ale dokumentacja i swagger nie mówi nic o zabronionych znakach...
