### ISSUE TITLE
Błąd dokumentacji swagger.yaml Location.City

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2247]
Występuje problem: 
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**
```
REQUEST 2019-09-20 07:30:12.4873204
curl -X PUT \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206582972' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"49abb879-c496-4934-8eec-8007a418d68e"},"returnPolicy":{"id":"d128a776-2353-43d1-8078-fce584ad3221"},"warranty":{"id":"a8b7c053-7d2c-40a1-8253-18ae2f8a50cb"}},"category":{"id":"253766"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":{"additionalInfo":"","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"c5e3d1bd-8ecc-42a1-8b1d-4dd961ae0fbd"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>tttt</p>\r\n"}]}]},"ean":null,"external":{"id":"DZ4"},"id":"6206582972","images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1102d5/84d8326d4d49a33b3e74a2f8b2d1"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11d857/8c42133c41c8b74687b45b23e791"}],"location":{"city":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","countryCode":"PL","postCode":"22-222","province":"DOLNOSLASKIE"},"name":"qweqwe","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]}],"payments":{"invoice":"NO_INVOICE"},"product":null,"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"245.00","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":1,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

RESPONSE 2019-09-20 07:30:15.9289701 Duration: 3441,6497ms
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "49abb879-c496-4934-8eec-8007a418d68e"
      },
      "ReturnPolicy": {
        "Id": "d128a776-2353-43d1-8078-fce584ad3221"
      },
      "Warranty": {
        "Id": "a8b7c053-7d2c-40a1-8253-18ae2f8a50cb"
      }
    },
    "Category": {
      "Id": "253766"
    },
    "CompatibilityList": null,
    "Contact": null,
    "CreatedAt": "2019-09-18T12:19:49Z",
    "Delivery": {
      "AdditionalInfo": "",
      "HandlingTime": "PT24H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "c5e3d1bd-8ecc-42a1-8b1d-4dd961ae0fbd"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "TEXT",
              "Content": "<p>tttt</p>\r\n"
            }
          ]
        }
      ]
    },
    "Ean": null,
    "External": {
      "Id": "DZ4"
    },
    "Id": "6206582972",
    "Images": [
      {
        "Url": "https://a.allegroimg.allegrosandbox.pl/original/1102d5/84d8326d4d49a33b3e74a2f8b2d1"
      },
      {
        "Url": "https://a.allegroimg.allegrosandbox.pl/original/11d857/8c42133c41c8b74687b45b23e791"
      }
    ],
    "Location": {
      "City": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "CountryCode": "PL",
      "PostCode": "22-222",
      "Province": "DOLNOSLASKIE"
    },
    "Name": "qweqwe",
    "Parameters": [
      {
        "Id": "11323",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "11323_1"
        ]
      }
    ],
    "Payments": {
      "Invoice": "NO_INVOICE"
    },
    "Product": null,
    "Promotion": {
      "Bold": false,
      "DepartmentPage": false,
      "Emphasized": false,
      "EmphasizedHighlightBoldPackage": false,
      "Highlight": false
    },
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": null,
      "EndingAt": null,
      "StartingAt": null,
      "Republish": false
    },
    "SellingMode": {
      "Format": "BUY_NOW",
      "Price": {
        "Amount": "245",
        "Currency": "PLN"
      },
      "MinimalPrice": null,
      "StartingPrice": null
    },
    "SizeTable": null,
    "Stock": {
      "Available": 1,
      "Unit": "UNIT"
    },
    "UpdatedAt": "2019-09-20T05:30:15.792Z",
    "Validation": {
      "Errors": [
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "ERR_LOCATION_TOO_LONG",
          "Path": "",
          "UserMessage": "Nazwa miejscowości w polu Lokalizacja jest zbyt długa."
        }
      ],
      "ValidatedAt": "2019-09-20T05:30:15.792Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "e9ed749ba5708070",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```

Dzień dobry, jak wynika z powyższego requestu wprowadzona została za długa nazwa miejscowości. Dokumentacja [2019-09-20] swagger.yaml zawiera informację, że można wprowadzić do 50 znaków:

```
Location:
      type: object
      description: for offer with a delivery method it is a parcel dispatch location. For offers with personal pick-up it is a pick-up location, additionally we recommend to use points of service (<a href="../../documentation/#tag/Points-of-service" target="_blank">https://developer.allegro.pl/documentation/#tag/Points-of-service</a>)
      properties:
        city:
          type: string
          maxLength: 50
```

Przez www sandbox jest walidacja na 35 znaków:

![Przechwytywanie](https://user-images.githubusercontent.com/8465007/65302183-a0190c80-db7a-11e9-82a2-59d20b7b3261.PNG)

Proszę o weryfikację poprawności całej dokumentacji pod kątem walidacji danych, zgłaszanej między innymi w wątku #1725.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, w najbliższym czasie zaktualizujemy dokumentację.

**Comment by alekskuc** [comment]
Dzień dobry, dziękuje za poprawienie dokumentacji w kwestii długości pola Miejscowość.

Proszę dodatkowo o dodanie wymagalności poniższych pól w obiekcie Location w pliku swagger.yaml [2019-09-24].

```
Location:
      type: object
      required:
        - city
        - countryCode
        - postCode
        - province
      description: for offer with a delivery method it is a parcel dispatch location. For offers with personal pick-up it is a pick-up location, additionally we recommend to use points of service (<a href="../../documentation/#tag/Points-of-service" target="_blank">https://developer.allegro.pl/documentation/#tag/Points-of-service</a>)
      properties:
        city:
          type: string
          maxLength: 35
        countryCode:
          type: string
        postCode:
          type: string
        province:
          type: string
          maxLength: 50
```

![image](https://user-images.githubusercontent.com/8465007/65505192-f06cd300-dec8-11e9-854f-b1ceadec8f22.png)

**Comment by frankii91** [comment]
uu miejscowość na 35 znaków to jest mało i często zdarza się że klienci piszą coś w stylu "XXX koło czegoś tam"  .. i wtedy robi się problem ...

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc - w odniesieniu do draftu wymagane jest tylko name, po utworzeniu takiego draftu otrzymasz informacje w sekcji errors, jakie pola są wymagane, aby oferta była kompletna i można ją było poprawnie opublikować,
@frankii91 - wystarczy wpisać prawidłowy kod pocztowy, wtedy nie jest konieczne dopisywanie dodatkowych informacji do miejscowości.

**Comment by frankii91** [comment]
ok,

Co do wysyłki Z  - tak naprawdę jak prawidłowo powinno się stosować ten parametr i jaki on ma znaczenie na wyświetlanie dla klienta ? i po co on jest ?

**Comment by PrzemyslawLukanowski** [comment]
Nie do końca rozumiem pytanie, jak prawidłowo powinno się stosować ten parametr. Wpisujesz miasto, z jakiego jest wysyłany przedmiot. Jest to informacja dla klienta, może jej użyć np. jako filtru w wyszukiwarce, aby odnaleźć oferty z odbiorem osobistym niedaleko swojej lokalizacji.

**Comment by alekskuc** [comment]
> @alekskuc - w odniesieniu do draftu wymagane jest tylko name, po utworzeniu takiego draftu otrzymasz informacje w sekcji errors, jakie pola są wymagane, aby oferta była kompletna i można ją było poprawnie opublikować

```
Location:
      type: object
      required:
        - city
        - countryCode
        - postCode
        - province
```

Dzień dobry, rozumiem, że sprawia problemy dodanie wymagalności na obiekcie Location w/w pól które wchodzą w skład obiektu Offer ze względu na to że nie ma odrębnego zasobu do walidacji draftów opisana w wątku #1911 ?

```
"Validation": {
      "Errors": [
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "Handling time may not be empty.",
          "Path": "",
          "UserMessage": "Czas wysyłki nie może być pusty."
        },
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "Location may not be empty.",
          "Path": "",
          "UserMessage": "Lokalizacja nie może być pusta."
        },
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "Uzupełnij parametry obowiązkowe: Stan.",
          "Path": "",
          "UserMessage": "Uzupełnij parametry obowiązkowe: Stan."
        },
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "Dodaj opis oferty.",
          "Path": "",
          "UserMessage": "Dodaj opis oferty."
        },
        {
          "Code": "VALIDATION_ERROR",
          "Details": "",
          "Message": "Warunki oferty (zwroty, reklamacje) są wymagane dla kont firma.",
          "Path": "",
          "UserMessage": "Warunki oferty (zwroty, reklamacje) są wymagane dla kont firma."
        }
      ],
      "ValidatedAt": "2019-09-25T06:09:22.365Z"
    }
  }
```

Proszę mi zatem wyjaśnić jak sensownie powiązać np. pole Offer.Location.City ze zwracaną walidacją z serwera rest api w celu zbudowania serwerowej walidacji na formularzu?

Zaznaczam tutaj, że założeniem jest aby formularz był odporny na zmiany w walidacji pól i był budowany dynamicznie, ze względu na częste zmiany w rest api.

Walidacja na stronie www.allegro.pl.allegrosandbox.pl w wewnętrznym zasobie allegro.pl.allegrosandbox.pl/offer-api/offers/ ma obiekt walidacji w postaci:

```
"validation":{ 
   "errors":[ 
      { 
         "code":"ConstraintViolationException.NotNull",
         "message":"Wystawiana liczba nie może być mniejsza niż 1.",
         "details":"Invalid value: null, Annotation: @javax.validation.constraints.NotNull(message={pl.allegro.offercore.offer.stock.initialQuantity.min}, payload=[], groups=[interface pl.allegro.offercore.service.server.model.validation.groups.StockValidation])",
         "path":"stock.initialQuantity",
         "userMessage":"Wystawiana liczba nie może być mniejsza niż 1."
      }
   ],
   "validatedAt":"2019-09-26T08:38:47.963Z"
}
```
Gdzie śmiało można powiązać walidację z polami z obiektu.

Skoro dodanie required w obiekcie Location jest problematyczne, to proszę o dodanie do rest api informacji jakie pole z obiektu Offer nie przeszło walidacji analogicznie do w/w "path":"stock.initialQuantity".
