### ISSUE TITLE
Błąd dokumentacji i swagger.yaml GET sale/offers/{offerId} additionalInfo.maxLength

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2866]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Występuje nieścisłość w dokumentacji i swagger.yaml . Pole informacji o dostawie może mieć więcej niż 500 znaków.

swagger.yml
```
    Delivery:
      type: object
      properties:
        additionalInfo:
          type: string
          maxLength: 500
```

Zasób GET sale/offers/{offerId}

> additionalInfo | string <= 500 characters

Przykładowy trace-id gdzie opis na aukcji ma 615 znaków:
trace-id:bd385b4d55ba98ae
