### ISSUE TITLE
Błąd dokumentacji swagger.yaml OfferListingDtoV1Stock.available.minimum

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#4003]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,

W swagger.yml w definicji OfferListingDtoV1Stock widnieje

```
    OfferListingDtoV1Stock:
      type: object
      description: Information on the offer's stock.
      properties:
        available:
          type: integer
          minimum: 1
          description: The available stock value.
          example: 23
        sold:
          type: integer
          minimum: 0
          description: The number of sold items in the last 30 days.
          example: 3
```

available.minimum 1 jest niepoprawna ponieważ może przyjąć wartość 0 - aukcja zakończona przez zakup ostatniej sztuki. 

Przykład:

`GET sale/offers?limit=10&offset=470&publication.status=ACTIVE%2CENDED&sellingMode.format=BUY_NOW`

`trace-id:25e1ae3ba30520fa`

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie błędu w dokumentacji. Poprawimy to.

**Comment by Radeq** [comment]
@AureliuszBrussy , dziękuję, przy okazji czy w swagger.yml w CheckoutForm.updatedAt nie brakuje
` format: date-time`
tak jest w innych własnościach daty? Np. SaleProductOfferResponse

```
    CheckoutForm:
        updatedAt:
          type: string
          description: 'Provided in [ISO 8601 format](link: https://en.wikipedia.org/wiki/ISO_8601).'
          example: '2011-12-03T10:15:30.133Z'

    SaleProductOfferResponse:
            updatedAt:
              type: string
              format: date-time
              description: >-
                Last update date: Format (ISO 8601) - yyyy-MM-dd'T'HH:mm:ss.SSSZ.
                Cannot be modified.
```

Podobnie brakuje tego w Pos.createdAt, Pos.updatedAt
