### ISSUE TITLE
Produktyryzacja - wyszukiwanie po EAN i zero na początku

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#4086]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Wykryłem problem z zasobem wyszukiwania produktów do ofert po EAN.

`GET sale/products?ean={string}`

Problem polega na niewyszukiwaniu niektórych produktów, dla których EAN rozpoczyna się od "0" (czyli 0 + 12 cyfr). Dla jednych produktów Allegro zwraca ten sam produkt obojętnie czy podamy 12 cyfr czy "0" + 12 cyfr. Dla innych zwraca tylko jak podamy 12 cyfr.

```
GET sale/products?ean=0xxx || trace-id:2e936d667ee8b3a8
GET sale/products?ean=xxx || trace-id:2e3c62ff50a80cf9
```
Dla powyższego, w pierwszym zapytaniu nie otrzymuję produktu, w drugim tak

```
GET sale/products?ean=0yyy || trace-id:8dfc8a3dde0a540f
GET sale/products?ean=yyy || trace-id:ed933c28ab6d320a
```
Dla powyższego, w obu zapytaniach otrzymuję produkt o tym samym id

Przy okazji swagger.yml informuje mnie, że name może mieć 50 znaków. Ja mam oferty z powyżej 200 znaków. Przykład https://allegro.pl/produkt/5a427909-cbee-49bc-a1a9-d99d24ff3696

```
    BaseSaleProductResponseDto:
      properties:
        name:
          type: string
          description: Name of the product.
          maxLength: 50
```
