### ISSUE TITLE
Braki w pliku yaml

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6707]
Dzień dobry,
w pliku yaml, pole typ obiektu "BadgeCampaign" prezentuje się następująco : 
```
type:
          type: string
          enum:
            - DISCOUNT
            - STANDARD
            - SOURCING
```
Jednak podczas pobierania kampanii przychodzi wpis z typem "CUSTOM_LABEL". Prosiłbym o weryfikację i ewentualne dodanie nowe typu do pliku.

Dodam, że próbowałem pobierać tylko na sandboxie jeżeli to coś zmienia
