### ISSUE TITLE
Nie możemy wyświetlić strony

### ISSUE THREAD

**Issue by xiongdg** [allegro/allegro-api#6801]
Hi team
I am testing allegro api on test environment, but now it reports below messages after I log in. 
```
Nie możemy wyświetlić strony
Numer błędu: c8129447b3b59130
```
I am using this configuration.
```
  security:
    oauth2:
      client:
        registration:
          allegro:
            clientId: 520b22c8a1374106a2233892a1ff3563
            clientSecret: ***
            redirectUri: http://localhost:8080/allegro/auth/callback
            scope: allegro:api
        provider:
          allegro:
            authorizationUri: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize
            tokenUri: https://allegro.pl.allegrosandbox.pl/auth/oauth/token
```
Any ideas? Thanks in advance!
